import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Plane, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';

const LandingHero = () => {
  const navigate = useNavigate();

  return (
    <header className="relative overflow-hidden" aria-label="Voyexa introduction">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-24 sm:pt-32 sm:pb-40">
        <div className="text-center space-y-8">
          {/* Logo/Brand */}
          <div className="flex justify-center items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-500 flex items-center justify-center">
              <Plane aria-hidden="true" className="w-6 h-6 text-white" />
            </div>
            <span className="text-2xl font-bold">Voyexa</span>
          </div>

          {/* Main Headline */}
          <div className="space-y-4 max-w-4xl mx-auto">
            <h1 className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-bold leading-tight tracking-tight">
              Your itinerary,{' '}
              <span
                className="bg-gradient-to-r from-indigo-400 via-violet-400 to-blue-400 bg-clip-text text-transparent animate-pulse"
                style={{ animationDuration: '4s' }}
              >
                built in seconds
              </span>
            </h1>
            <p className="text-lg sm:text-xl text-white/80 max-w-2xl mx-auto font-medium">
              AI-powered travel planning that creates detailed, day-by-day itineraries tailored to your budget, pace, and interests.
            </p>
            <p className="text-sm text-white/40 max-w-2xl mx-auto">
              No account needed to explore. Sign in to save your trips.
            </p>
          </div>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-y-3 sm:gap-y-0 sm:gap-x-4 pt-4">
            <Button
              data-testid="hero-get-started-btn"
              onClick={() => navigate('/auth')}
              size="lg"
              className="bg-indigo-500 hover:bg-indigo-600 text-white px-8 py-6 text-lg font-semibold rounded-xl transition-all duration-200 shadow-lg hover:shadow-indigo-500/25 w-full sm:w-auto focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 focus-visible:ring-offset-[#020617] focus-visible:outline-none"
            >
              <Sparkles aria-hidden="true" className="w-5 h-5 mr-2" />
              Get started
            </Button>
            <Button
              data-testid="hero-plan-trip-btn"
              onClick={() => navigate('/create-trip')}
              size="lg"
              variant="outline"
              className="border-2 border-white/20 hover:border-white/40 bg-white/5 backdrop-blur-sm text-white px-8 py-6 text-lg font-semibold rounded-xl transition-all duration-200 w-full sm:w-auto focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 focus-visible:ring-offset-[#020617] focus-visible:outline-none"
            >
              Plan a trip
            </Button>
          </div>

          {/* Sample itinerary preview (desktop only) */}
          <div className="hidden md:block pt-10">
            <div className="max-w-2xl mx-auto text-left">
              <p className="text-xs font-semibold uppercase tracking-wider text-white/50 mb-3">
                Sample itinerary
              </p>
              <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6">
                <div className="flex items-start justify-between gap-6 mb-5">
                  <div>
                    <h3 className="text-lg font-bold tracking-tight">Tokyo, Japan</h3>
                    <p className="text-sm text-white/60">5 days • Balanced pace</p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs text-white/50">Generated by Voyexa</p>
                    <p className="text-sm font-semibold text-indigo-300">Day 1 (preview)</p>
                  </div>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/5 px-4 py-3">
                    <div className="flex items-center gap-3">
                      <span className="w-2.5 h-2.5 rounded-full bg-amber-400" />
                      <span className="text-sm font-semibold text-white/80">Morning</span>
                    </div>
                    <span className="text-sm text-white">Senso-ji Temple</span>
                  </div>

                  <div className="flex items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/5 px-4 py-3">
                    <div className="flex items-center gap-3">
                      <span className="w-2.5 h-2.5 rounded-full bg-sky-400" />
                      <span className="text-sm font-semibold text-white/80">Afternoon</span>
                    </div>
                    <span className="text-sm text-white">Shibuya Crossing</span>
                  </div>

                  <div className="flex items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/5 px-4 py-3">
                    <div className="flex items-center gap-3">
                      <span className="w-2.5 h-2.5 rounded-full bg-violet-400" />
                      <span className="text-sm font-semibold text-white/80">Evening</span>
                    </div>
                    <span className="text-sm text-white">Shinjuku Gyoen</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Subtle trust indicator */}
          <div className="pt-8 flex items-center justify-center gap-2 text-sm text-white/60">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
            <span>Powered by advanced AI</span>
          </div>
        </div>
      </div>
    </header>
  );
};

export default LandingHero;

